# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first-design.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")
        self.horizontal_layout = QtWidgets.QHBoxLayout()
        self.horizontal_layout.setObjectName("horizontal_layout")
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontal_layout)
        self.button_add_client = QtWidgets.QPushButton(self.centralwidget)
        self.button_add_client.setObjectName("button_add_client")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.button_add_client)
        self.grid_layout = QtWidgets.QGridLayout()
        self.grid_layout.setObjectName("grid_layout")
        self.label_disk2 = QtWidgets.QLabel(self.centralwidget)
        self.label_disk2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_disk2.setObjectName("label_disk2")
        self.grid_layout.addWidget(self.label_disk2, 0, 1, 1, 1)
        self.label_disk3 = QtWidgets.QLabel(self.centralwidget)
        self.label_disk3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_disk3.setObjectName("label_disk3")
        self.grid_layout.addWidget(self.label_disk3, 0, 2, 1, 1)
        self.label_disk1 = QtWidgets.QLabel(self.centralwidget)
        self.label_disk1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_disk1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_disk1.setObjectName("label_disk1")
        self.grid_layout.addWidget(self.label_disk1, 0, 0, 1, 1)
        self.label_disk4 = QtWidgets.QLabel(self.centralwidget)
        self.label_disk4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_disk4.setObjectName("label_disk4")
        self.grid_layout.addWidget(self.label_disk4, 0, 3, 1, 1)
        self.label_disk5 = QtWidgets.QLabel(self.centralwidget)
        self.label_disk5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_disk5.setObjectName("label_disk5")
        self.grid_layout.addWidget(self.label_disk5, 0, 4, 1, 1)
        self.progress_bar_disk1 = QtWidgets.QProgressBar(self.centralwidget)
        self.progress_bar_disk1.setProperty("value", 24)
        self.progress_bar_disk1.setObjectName("progress_bar_disk1")
        self.grid_layout.addWidget(self.progress_bar_disk1, 1, 0, 1, 1)
        self.progress_bar_disk2 = QtWidgets.QProgressBar(self.centralwidget)
        self.progress_bar_disk2.setProperty("value", 24)
        self.progress_bar_disk2.setObjectName("progress_bar_disk2")
        self.grid_layout.addWidget(self.progress_bar_disk2, 1, 1, 1, 1)
        self.progress_bar_disk3 = QtWidgets.QProgressBar(self.centralwidget)
        self.progress_bar_disk3.setProperty("value", 24)
        self.progress_bar_disk3.setObjectName("progress_bar_disk3")
        self.grid_layout.addWidget(self.progress_bar_disk3, 1, 2, 1, 1)
        self.progress_bar_disk4 = QtWidgets.QProgressBar(self.centralwidget)
        self.progress_bar_disk4.setProperty("value", 24)
        self.progress_bar_disk4.setObjectName("progress_bar_disk4")
        self.grid_layout.addWidget(self.progress_bar_disk4, 1, 3, 1, 1)
        self.progress_bar_disk5 = QtWidgets.QProgressBar(self.centralwidget)
        self.progress_bar_disk5.setProperty("value", 24)
        self.progress_bar_disk5.setObjectName("progress_bar_disk5")
        self.grid_layout.addWidget(self.progress_bar_disk5, 1, 4, 1, 1)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.grid_layout)
        self.button_start = QtWidgets.QPushButton(self.centralwidget)
        self.button_start.setObjectName("button_start")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.button_start)
        self.button_stop = QtWidgets.QPushButton(self.centralwidget)
        self.button_stop.setObjectName("button_stop")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.button_stop)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_add_client.setText(_translate("MainWindow", "Add Client"))
        self.label_disk2.setText(_translate("MainWindow", "Disk 2"))
        self.label_disk3.setText(_translate("MainWindow", "Disk 3"))
        self.label_disk1.setText(_translate("MainWindow", "Disk 1"))
        self.label_disk4.setText(_translate("MainWindow", "Disk 4"))
        self.label_disk5.setText(_translate("MainWindow", "Disk 5"))
        self.button_start.setText(_translate("MainWindow", "Start"))
        self.button_stop.setText(_translate("MainWindow", "Stop"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
